import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto flex flex-col space-y-4">
          <header className="container sticky top-0 z-40 bg-white">
            <div className="h-16 border-b border-b-slate-200 py-4">
              <nav className="ml-4 pl-6 flex justify-around">
                <Link href="/" className="hover:text-slate-600 cursor-pointer">
                  Home
                </Link>
                <Link href="/data">AI Data</Link>
              </nav>
            </div>
          </header>
          <div>
            <main className="flex w-full flex-1 flex-col overflow-hidden">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
